# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:30'
      timezone: 'Asia/Tokyo'
    versioning-strategy: 'lockfile-only'
    # open-pull-requests-limit: 10 # MEMO:要調整
    ignore:
      - dependency-name: 'storybook' # MEMO: 関連パッケージ全てでバージョンを揃える必要があるため手動で行う
        versions: ['7.x.x']
